name: Download and Build Pixiv

on:
  workflow_dispatch:
  schedule:
    # Once a day at midnight
    - cron: '0 0 * * *'

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Fetch Database
        run: bun run fetch-db

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build Dictionary
        run: |
          bun run buildPixiv -- --tagName ${{ steps.date.outputs.date }}
          bun run buildPixivLight -- --tagName ${{ steps.date.outputs.date }}

      - name: Create and Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is an automated release of the latest Pixiv for Yomitan.
            Please check the [README](https://github.com/MarvNC/pixiv-yomitan) for more information.
